# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./swGUI/GUI.sln
  TOOLSET: v143
  ARCH: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Release, Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-architecture: ${{env.ARCH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /verbosity:minimal /p:Configuration=${{matrix.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Move target binaries
      shell: bash
      run: |
        mkdir tests-bins
        mkdir tests-bins/swCommonLib
        mkdir tests-bins/swGraphicAPI
        mkdir tests-bins/swGeometrics
        cp swCommonLib/_Target/${{matrix.BUILD_CONFIGURATION}}-${{env.ARCH}}-${{env.TOOLSET}}/TestsDir/* tests-bins/swCommonLib
        cp swGraphicAPI/_Target/${{matrix.BUILD_CONFIGURATION}}-${{env.ARCH}}-${{env.TOOLSET}}/TestsDir/* tests-bins/swGraphicAPI
        cp swGeometrics/_Target/${{matrix.BUILD_CONFIGURATION}}-${{env.ARCH}}-${{env.TOOLSET}}/TestsDir/* tests-bins/swGeometrics
        ls -al tests-bins/swCommonLib
        ls -al tests-bins/swGraphicAPI
        ls -al tests-bins/swGeometrics

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{matrix.BUILD_CONFIGURATION}}
        path: tests-bins

  test:
    runs-on: windows-latest
    needs: build
    strategy:
      matrix:
        sub-project: [swCommonLib, swGraphicAPI, swGeometrics]
        # , swGUI, swInputLibrary
    env:
      TEST_BUILD_CONFIGURATION: Debug
    steps:
      - uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: artifacts-${{env.TEST_BUILD_CONFIGURATION}}
          path: test-binaries
      
      - name: Move Test Resources
        shell: bash
        run: |
          mkdir -p workdir/${{matrix.sub-project}}
          cp -r ${{matrix.sub-project}}/TestResources/* workdir/${{matrix.sub-project}}/ || :
          ls -al .
          ls -al workdir
          ls -al workdir/${{matrix.sub-project}}
      
      - name: Run Tests
        shell: bash
        run: python3 run-tests.py test-binaries/${{matrix.sub-project}} workdir/${{matrix.sub-project}}

